# Generated by Django 5.2.15 on 2026-06-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pdesc', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('pcategory', models.CharField(max_length=30)),
                ('trending', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('pimage', models.ImageField(default='Default.jpg', upload_to='uploads/')),
            ],
        ),
    ]
