# Generated by Django 5.2.15 on 2026-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
