# Generated by Django 5.2.15 on 2026-06-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_cartmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
